version: '3.8'

# Development overrides for docker-compose.yml

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bug_repro_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"

  nats:
    ports:
      - "4222:4222"
      - "8222:8222"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    volumes:
      - ./apps/api/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug

  frontend:
    volumes:
      - ./apps/frontend/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  postgres_dev_data:
    driver: local
